# Generated by Django 5.2.5 on 2025-10-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='borrado',
        ),
    ]
