# Generated by Django 5.2.5 on 2025-10-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='clientes.cliente'),
        ),
    ]
