# Generated by Django 5.2.5 on 2025-10-13 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cantidad', models.CharField(default='0', max_length=10, validators=[django.core.validators.RegexValidator(message='Solo dígitos permitidos', regex='^\\d+$')], verbose_name='Cantidad de Clases')),
                ('precio', models.CharField(default='0.00', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato inválido: use solo números con hasta dos decimales', regex='^\\d+(\\.\\d{1,2})?$')], verbose_name='Precio')),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
            ],
        ),
    ]
