# Generated by Django 5.2.5 on 2025-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='dias_semana',
            field=models.IntegerField(default=3),
        ),
    ]
