# Generated by Django 5.2.5 on 2025-10-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('emergencia', models.CharField(blank=True, max_length=20, verbose_name='Emergencia')),
                ('domicilio', models.CharField(blank=True, max_length=100, verbose_name='Domicilio')),
            ],
        ),
    ]
