# Generated by Django 5.2.5 on 2025-11-27 16:47

import clientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100, validators=[clientes.models.validar_nombre])),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100, validators=[clientes.models.validar_nombre])),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (7-8 dígitos)', max_length=8, validators=[clientes.models.validar_dni])),
                ('telefono', models.CharField(blank=True, default='0000000000', help_text='Teléfono principal de contacto', max_length=20, validators=[clientes.models.validar_telefono])),
                ('emergencia', models.CharField(blank=True, default='No especificado', help_text='Teléfono de emergencia', max_length=20, validators=[clientes.models.validar_telefono])),
                ('domicilio', models.CharField(blank=True, default='No especificado', help_text='Dirección del cliente', max_length=200)),
                ('email', models.EmailField(blank=True, default='No especificado', help_text='Correo electrónico', max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un email válido')])),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['dni'], name='clientes_cl_dni_5e5da9_idx'), models.Index(fields=['apellido', 'nombre'], name='clientes_cl_apellid_894bd6_idx'), models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx')],
            },
        ),
    ]
