# Generated by Django 5.2.5 on 2025-11-14 15:03

import clientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el cliente está activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(help_text='Apellido del cliente', max_length=100, validators=[clientes.models.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(help_text='Documento Nacional de Identidad (7-8 dígitos)', max_length=8, validators=[clientes.models.validar_dni]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(blank=True, default='No especificado', help_text='Dirección del cliente', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='No especificado', help_text='Correo electrónico', max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un email válido')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='emergencia',
            field=models.CharField(blank=True, default='No especificado', help_text='Teléfono de emergencia', max_length=20, validators=[clientes.models.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre del cliente', max_length=100, validators=[clientes.models.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='0000000000', help_text='Teléfono principal de contacto', max_length=20, validators=[clientes.models.validar_telefono]),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['dni'], name='clientes_cl_dni_5e5da9_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellido', 'nombre'], name='clientes_cl_apellid_894bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx'),
        ),
    ]
