# Generated by Django 5.2.5 on 2025-10-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField()),
                ('clases_restantes', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='clientes.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
        ),
    ]
