# Generated by Django 5.2.5 on 2025-10-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='observaciones',
            field=models.TextField(blank=True, default='Ninguna'),
        ),
    ]
