# Generated by Django 5.2.5 on 2025-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_activo_and_more'),
        ('membresias', '0002_membresia_observaciones'),
        ('servicios', '0002_servicio_dias_semana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresia',
            options={'ordering': ['-activa', '-fecha_inicio'], 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AlterField(
            model_name='membresia',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la membresía está activa'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='clases_restantes',
            field=models.IntegerField(default=0, help_text='Cantidad de clases restantes para esta membresía'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='observaciones',
            field=models.TextField(blank=True, default='Ninguna', help_text='Observaciones adicionales sobre la membresía'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(fields=['activa', 'fecha_fin'], name='membresias__activa_b9c1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(fields=['cliente', 'activa'], name='membresias__cliente_f64c2f_idx'),
        ),
    ]
