# Generated by Django 5.2.5 on 2025-11-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_activo_and_more'),
        ('membresias', '0004_alter_membresia_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='clientes.cliente'),
        ),
    ]
