# Generated by Django 5.2.5 on 2025-10-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tipo',
        ),
    ]
